apiVersion: v1
kind: Service
metadata:
  name: status-server-svc
  labels:
    run: status-server-svc
spec:
  ports:
    - port: 80
      targetPort: 7979
      protocol: TCP
  selector:
    run: status-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-server
spec:
  selector:
    matchLabels:
      run: status-server
  replicas: 1
  template:
    metadata:
      labels:
        run: status-server
    spec:
      volumes:
        - name: nfs-pv
          persistentVolumeClaim:
            claimName: collector-pvc
      containers:
        - name: carbon-webhook
          image: washraf/status-server:latest
          imagePullPolicy: Always
          args:
            - "--carbon-hook=http://carbon-service-svc"
            - "--watch-period=1"
            - "--logs-location=/nfs"
            - "--address=http://status-server-svc"
          ports:
            - containerPort: 7979
          resources:
              limits:
                cpu: 1
                memory: 2Gi
          volumeMounts:
            - mountPath: /nfs
              name: nfs-pv