apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collector-pvc
  namespace: default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi