---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - carbonscaler.io
  resources:
  - carbonscalermpijobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - carbonscaler.io
  resources:
  - carbonscalermpijobs/finalizers
  verbs:
  - update
- apiGroups:
  - carbonscaler.io
  resources:
  - carbonscalermpijobs/status
  verbs:
  - get
  - patch
  - update
